version: '3.7'

services:
  hooligan-stream-service:
    image: hooliganstreamservice
    build: .
    ports:
      - 3000:3000
      
  redis-db:
    image: "bitnami/redis"
    volumes:
      - ./data/redis:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=terrence
    ports:
      - "6379:6379"
 
