version: '3.4'

services:
  hooliganstreamservice:
    image: hooliganstreamservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
